#!/usr/bin/env bash
# vim: ft=bash
set -e

function linking() {
    ln -sfn $(pwd)/.zshrc ~/.zshrc
    ln -sfn $(pwd)/.zshenv ~/.zshenv
    ln -sfn $(pwd)/.tmux.conf ~/.tmux.conf
    ln -sfn $(pwd)/.psqlrc ~/.psqlrc
    ln -sfn $(pwd)/.vimrc ~/.vimrc
    ln -sfn $(pwd)/.ideavimrc ~/.ideavimrc
    ln -sfn $(pwd)/.ripgreprc ~/.ripgreprc

    mkdir -p ~/.local/bin
    mkdir -p ${XDG_DATA_HOME:=~/.local/share}
    mkdir -p ${XDG_CONFIG_HOME:=~/.config}
    ln -sfn $(pwd)/ghostty $XDG_CONFIG_HOME/ghostty
    ln -sfn $(pwd)/nvim $XDG_CONFIG_HOME/nvim

    ln -sfn $(pwd)/.gitignore ~/.gitignore
    git config --global core.excludesFile ~/.gitignore
    git config --global diff.tool 'nvim -d'
    git config --global merge.tool 'nvim -d'
    git config --global merge.conflictstyle diff3

    touch ~/.profile
    mkdir -p ~/personal
    mkdir -p ~/repos
}

echo '[-] linking dotfiles [-]'
linking  # link first to avoid any potential issues

if [ "$(uname -s)" = "Darwin" ]; then  # macos
    if ! xcode-select -p &> /dev/null; then
        echo '[-] installing xcode command line tools [-]'
        xcode-select --install
    fi

    if ! command -v brew &> /dev/null; then
        echo '[-] installing homebrew [-]'
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)"
    fi

    echo '[-] installing essential packages [-]'
    brew update
    brew install curl wget git coreutils watch cmake ninja tree parallel ncdu
    brew install ghostty tmux ripgrep jq gdb universal-ctags
else  # linux or wsl
    echo '[-] checking secure boot state [-]' && \
        [ ! -f /etc/wsl.conf ] && [[ "$(mokutil --sb-state)" != *"SecureBoot enabled"* ]] && \
        echo "could not determine the secure boot state." && exit 1

    echo '[-] installing essential packages [-]'
    sudo dnf upgrade -y
    sudo dnf install -y curl wget zip zsh git coreutils gcc clang clangd cmake make ninja-build
    sudo dnf install -y parallel ncdu watch tree vim tmux ripgrep gdb xxd jq wl-clipboard

    if lspci | grep -E "VGA|3D" | grep -iq "AMD" ; then
        echo '[-] enabling rpm fusion repositories [-]'
        sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
        sudo dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
        sudo dnf install -y rocm-smi steam
        ln -sfn $(pwd)/MangoHud ${XDG_DATA_HOME:=~/.local/share}/MangoHud
        echo '[!] example launch options letting wayland works correctly [!]'
        echo '`SDL_VIDEO_DRIVER=wayland SDL_VIDEO_WAYLAND_SCALE_TO_DISPLAY=1 gamemoderun %command%`'
    fi

    target_dir=${XDG_DATA_HOME:=~/.local/share}/ctags; \
        [ ! -d $target_dir ] && echo '[-] building ctags [-]' && \
        sudo dnf install -y autoconf automake pkg-config gcc make && \
        git clone --depth 1 https://github.com/universal-ctags/ctags $target_dir && \
        (cd $target_dir && ./autogen.sh && ./configure && make && sudo make install)

    target_dir=${XDG_DATA_HOME:=~/.local/share}/ibus-bamboo; \
        [ ! -f /etc/wsl.conf ] && [ ! -d $target_dir ] && echo '[-] building ibus-bamboo [-]' && \
        sudo dnf install -y ibus make go libX11-devel libXtst-devel gtk3-devel && \
        git clone --depth 1 https://github.com/BambooEngine/ibus-bamboo.git $target_dir && \
        (cd $target_dir && sudo make install PREFIX=/usr) && \
        env DCONF_PROFILE=ibus dconf write /desktop/ibus/general/preload-engines "['BambooUs', 'Bamboo']" && \
        gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'Bamboo')]"
fi

# apply for both macos and linux
echo '[-] downloading git-prompt.sh script [-]'
mkdir -p ~/.zsh/plugins/git/
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh \
    -o ~/.zsh/plugins/git/git-prompt.sh

target_dir=~/.zsh/zsh-autosuggestions; \
    [ ! -d $target_dir ] && echo '[-] cloning zsh-autosuggestions [-]' && \
    git clone https://github.com/zsh-users/zsh-autosuggestions $target_dir

target_dir=${XDG_DATA_HOME:=~/.local/share}/neovim; echo '[-] building neovim [-]'; \
    [ ! -d $target_dir ] && git clone https://github.com/neovim/neovim.git $target_dir; \
    (cd $target_dir && git pull --rebase && git checkout nightly && \
    make distclean && make CMAKE_BUILD_TYPE=RelWithDebInfo && sudo make install)

current_shell=$(echo $SHELL)
if [ "$current_shell" != '/usr/bin/zsh' ] && [ "$current_shell" != '/bin/zsh' ] ; then
    echo '[-] change default shell to zsh [-]'
    chsh -s $(which zsh)
    echo '[-] device ready, reboot your computer. [-]'
else
    echo '[-] device ready. [-]'
fi
